# Generated by Django 5.0.6 on 2024-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_card_card_coins_question_coins_user_coins_aval'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(default='Hindi', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='ogmedia',
            field=models.CharField(default='Movie', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='show_country',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='show_language',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='show_media',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='show_year',
            field=models.IntegerField(default=0),
        ),
    ]
