# Generated by Django 5.0.6 on 2024-12-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_show_country_alter_user_show_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rf_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rf_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
