# Generated by Django 5.0.6 on 2025-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
