# Generated by Django 5.0.6 on 2024-10-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_debreverberate_hallno_reverberate_hallno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debreverberate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reverberate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
