# Generated by Django 5.0.6 on 2024-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_debreverberate_email_alter_reverberate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debreverberate',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='reverberate',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
